# ENPM673 Project 2

#### Part1

In [13]:
#importing modules
from ast import Pass
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt

# Creating a VideoCapture object and reading from input file
cap = cv2.VideoCapture('proj2_v2.mp4')
#capturing the fps of the video
fps = cap.get(cv2.CAP_PROP_FPS)

#creating frame counter
frame_counter=0
print(f"{fps} Frames per second")

# Checking if camera opened successfully
if (cap.isOpened()== False):
  print("Error opening video stream or file")

# Reading until video is completed
while(cap.isOpened()):
  # Captureing frame-by-frame
  ret, frame = cap.read()
  if ret == True:
    #incrementing frame counter
    
    #Converting BGR to Graysclae to reduce the channel of colors
    image=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    #Variance of Laplacian
    # laplcian=cv2.Laplacian(frame,cv2.CV_64F)
    # laplacian_var=cv2.Laplacian(image,cv2.CV_64F).var()

    #******************************
    # Apply identity kernel
    kernel1 = np.array([[0, 1, 0],
                        [1, -4, 1],
                        [0, 1, 0]])
 
    identity = cv2.filter2D(src=image, ddepth=-1, kernel=kernel1)
    identity_var=identity.var()
    #updating variable text based on the threshold of variance of laplacian
    if identity_var>150:
        text="not blurry"
        frame_counter+=1
        #putting text on the frame
        # cv2.putText(frame, "{}: {:.2f}".format(text, laplacian_var), (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 3)
        #Smoothing the frames to eliminate the noise from the video frames
        # gblur = cv2.GaussianBlur(image, (15, 15), 0)
        # #--------------------------------------------------------------------
        # #Binary thresolding a grayscale frame to capture the moving dark object
        # ret,thres=cv2.threshold(image,205,255,cv2.THRESH_BINARY)
        # thres_lower = 500 # Lower Threshold 
        # thres_upper = 1520 # Upper threshold 
        
        # # Applying the Canny Edge filter with L2Gradient = True 
        # edge = cv2.Canny(thres, thres_lower, thres_upper) 
        # lines = cv2.HoughLinesP(
        #     edge, # Input edge image
        #     1, # Distance resolution in pixels
        #     np.pi/180, # Angle resolution in radians
        #     threshold=70, # Min number of votes for valid line
        #     minLineLength=80, # Min allowed length of line
        #     maxLineGap=10 # Max allowed gap between line for joining them
        #     )
        # # Iterate over points
        # for points in lines:
        #       # Extracted points nested in the list
        #     x1,y1,x2,y2=points[0]
        #     # Draw the lines joing the points
        #     # On the original image
        #     cv2.line(frame,(x1,y1),(x2,y2),(0,255,0),4)
        #-------------------------------------------------------------------------------------------
        # cv2.imshow('Frame',identity)
    elif identity_var<150:
      text="Blurry"
    #putting text on the frame
    cv2.putText(identity, "{}: {:.2f}".format(text, identity_var), (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 3)
    cv2.imshow('Frame',identity)
       
    # print(laplacian_var)
    # Press Q on keyboard to  exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break

  # Break the loop
  else:
    break

cap.release()
cv2.destroyAllWindows()



29.0 Frames per second


In [ ]:
 Apply identity kernel
kernel1 = np.array([[0, 0, 0],
                    [0, 1, 0],
                    [0, 0, 0]])
 
identity = cv2.filter2D(src=image, ddepth=-1, kernel=kernel1)
 

In [ ]:
# Default resolutions of the frame are obtained.The default resolutions are system dependent.
# We convert the resolutions from float to integer.
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
 
# Define the codec and create VideoWriter object.The output is stored in 'outpy.avi' file.
out = cv2.VideoWriter('outpy.avi',cv2.VideoWriter_fourcc('M','J','P','G'), 10, (frame_width,frame_height))
 
 #in while loop
 # Write the frame into the file 'output.avi'
    out.write(frame)

out.release()

In [11]:
#importing modules
from ast import Pass
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt

def findIntersection(points1,points2):
        x1,y1,x2,y2=points1[0]
        x3,y3,x4,y4=points2[0]
        deno_x=(x1-x2)*(y3-y4)-(y1-y2)*(x3-x4)
        num_x=(x1*y2-y1*x2)*(x3-x4)-(x1-x2)*(x3*y4-y3*x4) 
        deno_y=(x1-x2)*(y3-y4)-(y1-y2)*(x3-x4)
        num_y=(x1*y2-y1*x2)*(y3-y4)-(y1-y2)*(x3*y4-y3*x4)
        if deno_x!=0:
          px= ( num_x ) / ( deno_x ) 
        else:
           return ['nan','nan' ]
        if deno_y!=0:
          py= ( num_y ) / ( deno_y )
        else:
           return ['nan','nan' ]
        if np.isinf(px) or np.isinf(py):
           return ['nan','nan' ]
        else:
          return [int(px), int(py)]

# Creating a VideoCapture object and reading from input file
cap = cv2.VideoCapture('proj2_v2.mp4')
#capturing the fps of the video
fps = cap.get(cv2.CAP_PROP_FPS)

#creating frame counter
frame_counter=0
print(f"{fps} Frames per second")

# Checking if camera opened successfully
if (cap.isOpened()== False):
  print("Error opening video stream or file")
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
 
# Define the codec and create VideoWriter object.The output is stored in 'outpy.avi' file.
out = cv2.VideoWriter('outvideo.mp4',cv2.VideoWriter_fourcc(*'mp4v'), 10, (frame_width,frame_height))

# Reading until video is completed
while(cap.isOpened()):
  # Captureing frame-by-frame
  ret, frame = cap.read()
  if ret == True:
    #incrementing frame counter
    
    #Converting BGR to Graysclae to reduce the channel of colors
    image=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    #Variance of Laplacian
    # laplcian=cv2.Laplacian(frame,cv2.CV_64F)
    # laplacian_var=cv2.Laplacian(image,cv2.CV_64F).var()

    #******************************
    # Apply identity kernel
    kernel= np.array([[1, 1, 1],
                        [1, 1, 1],
                        [1, 1, 1]])
    kernel1 = np.array([[0, 1, 0],
                        [1, -4, 1],
                        [0, 1, 0]])
    kernel2 = np.array([[0, -1, 0],
                        [-1, 4, -1],
                        [0, -1, 0]])
 
    identity = cv2.filter2D(src=image, ddepth=cv2.CV_64F, kernel=kernel1)
    identity_var=identity.var()
    #updating variable text based on the threshold of variance of laplacian
    if identity_var>150:
        text="not blurry"
        frame_counter+=1
        #putting text on the frame
        # cv2.putText(frame, "{}: {:.2f}".format(text, laplacian_var), (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 3)
        #Smoothing the frames to eliminate the noise from the video frames
        # gblur = cv2.GaussianBlur(image, (15, 15), 0)
        # #--------------------------------------------------------------------
        # #Binary thresolding a grayscale frame to capture the moving dark object
        thres=np.where(image>=205, 255,0).astype(np.uint8)
        # ret,thres=cv2.threshold(image,205,255,cv2.THRESH_BINARY)
        img_ero = cv2.erode(thres, kernel, iterations=1)
        img_dil = cv2.dilate(img_ero, kernel, iterations=1)

        thres_lower = 80 # Lower Threshold 
        thres_upper = 240 # Upper threshold 
        
        # Applying the Canny Edge filter with L2Gradient = True 
        edge = cv2.Canny(img_dil, thres_lower, thres_upper) 

        # This returns an array of r and theta values
        # lines = cv2.HoughLines(edge, 1, np.pi/180, 70)
        
        # # print(lines)
        # # The below for loop runs till r and theta values
        # # are in the range of the 2d array
        # for r_theta in lines:
        #     arr = np.array(r_theta[0], dtype=np.float64)
        #     r, theta = arr
        #     # Stores the value of cos(theta) in a
        #     a = np.cos(theta)
        
        #     # Stores the value of sin(theta) in b
        #     b = np.sin(theta)
        
        #     # x0 stores the value rcos(theta)
        #     x0 = a*r
        
        #     # y0 stores the value rsin(theta)
        #     y0 = b*r
        
        #     # x1 stores the rounded off value of (rcos(theta)-1000sin(theta))
        #     x1 = int(x0 + 1000*(-b))
        
        #     # y1 stores the rounded off value of (rsin(theta)+1000cos(theta))
        #     y1 = int(y0 + 1000*(a))
        
        #     # x2 stores the rounded off value of (rcos(theta)+1000sin(theta))
        #     x2 = int(x0 - 1000*(-b))
        
        #     # y2 stores the rounded off value of (rsin(theta)-1000cos(theta))
        #     y2 = int(y0 - 1000*(a))

        #     print(x1,y1,x2,y2)
        #     # cv2.line draws a line in img from the point(x1,y1) to (x2,y2).
        #     # (0,0,255) denotes the colour of the line to be
        #     # drawn. In this case, it is red.
        #     cv2.line(frame, (x1, y1), (x2, y2), (0, 0, 255), 2)
        




        lines = cv2.HoughLinesP(
            edge, # Input edge image
            1, # Distance resolution in pixels
            np.pi/180, # Angle resolution in radians
            threshold=60, # Min number of votes for valid line
            minLineLength=100, # Min allowed length of line
            maxLineGap=5# Max allowed gap between line for joining them
            )
        
        
        

        
        # Iterate over points
        for points in lines:
              # Extracted points nested in the list
            x1,y1,x2,y2=points[0]
            # Draw the lines joing the points
            # On the original image
            x=0
            y=((y2-y1)/(x2-x1))*(-x2+x)+y2
            x_1=x
            y_1=int(y)

            x=720
            y=((y2-y1)/(x2-x1))*(-x2+x)+y2
           
            x_2=x
            y_2=int(y)
         

            # _lines.append([x_1,y_1,x_2,y_2])

            cv2.line(frame,(int (x_1),int (y_1)),(int (x_2),int (y_2)),(255,0,0),1)
            # cv2.line(frame,(int (x1),int (y1)),(int (x2),int (y2)),(0,255,0),4)
        # print(len(lines))
        for i in range(len(lines)-1):
           for j in range(len(lines)-i-1):
              corner=findIntersection(lines[i],lines[j+i+1])
              if corner[0]=='nan' or corner[1]=='nan':
                  continue
              else:
                frame = cv2.circle(frame, tuple(corner), 5, (0,0,255), -1)
        
        
        img_dil = np.float32(img_dil) 

        # apply the cv2.cornerHarris method 
        # to detect the corners with appropriate 
        # values as input parameters 
        dest = cv2.cornerHarris(img_dil, 5, 3, 0.07)
        
        frame[dest > 0.01 * dest.max()]=[0, 255, 0] 

        
        # frame[dest > 0.01 * dest.max()]=[0, 255, 0] 


        
        
        #-------------------------------------------------------------------------------------------
        # print(_lines)
        # cv2.imshow('Frame',frame)
    
    #putting text on the frame
    # cv2.putText(identity, "{}: {:.2f}".format(text, identity_var), (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 3)
    # cv2.imshow('Frame',identity)
    # cv2.imshow('Frame',frame) 

    out.write(frame)
    # print(laplacian_var)
    # Press Q on keyboard to  exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break

  # Break the loop
  else:
    break

out.release()
cap.release()
cv2.destroyAllWindows()



29.0 Frames per second


### Harris COrner Detection

In [7]:
# Python program to illustrate 
# corner detection with 
# Harris Corner Detection Method 

# organizing imports 
import cv2 
import numpy as np 

# Creating a VideoCapture object and reading from input file
cap = cv2.VideoCapture('proj2_v2.mp4')
#capturing the fps of the video
fps = cap.get(cv2.CAP_PROP_FPS)

#creating frame counter
frame_counter=0
print(f"{fps} Frames per second")

# Checking if camera opened successfully
if (cap.isOpened()== False):
  print("Error opening video stream or file")

# Reading until video is completed
while(cap.isOpened()):
  # Captureing frame-by-frame
  ret, frame = cap.read()
  if ret == True:
    #incrementing frame counter
    
    #Converting BGR to Graysclae to reduce the channel of colors
    image=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    #Variance of Laplacian
    # laplcian=cv2.Laplacian(frame,cv2.CV_64F)
    # laplacian_var=cv2.Laplacian(image,cv2.CV_64F).var()

    #******************************
    # Apply identity kernel
    kernel1 = np.array([[0, 1, 0],
                        [1, -4, 1],
                        [0, 1, 0]])
 
    identity = cv2.filter2D(src=image, ddepth=-1, kernel=kernel1)
    identity_var=identity.var()
    #updating variable text based on the threshold of variance of laplacian
    if identity_var>90:
        text="not blurry"
        frame_counter+=1
         # #Binary thresolding a grayscale frame to capture the moving dark object
        ret,thres=cv2.threshold(image,205,255,cv2.THRESH_BINARY)
        img_ero = cv2.erode(thres, kernel, iterations=1)
        img_dil = cv2.dilate(img_ero, kernel, iterations=1)
        # modify the data type 
        # setting to 32-bit floating point 
        img_dil = np.float32(img_dil) 

        # apply the cv2.cornerHarris method 
        # to detect the corners with appropriate 
        # values as input parameters 
        dest = cv2.cornerHarris(img_dil, 2, 5, 0.05) 

        # Results are marked through the dilated corners 
        # dest = cv2.dilate(dest, None) 

        # Reverting back to the original image, 
        # with optimal threshold value 
        frame[dest > 0.01 * dest.max()]=[0, 0, 255] 

        # the window showing output image with corners 
        cv2.imshow('Image with Borders', frame) 

    if cv2.waitKey(25) & 0xFF == ord('q'):
       break

  # Break the loop
  else:
    break

cap.release()
cv2.destroyAllWindows()


29.0 Frames per second


### Canny edge with the trackbar

##### Upper threshold: All the pixel values above threshold limit is considered
##### Lower Threshold: All the Pixel value below Threshold limit is discarded
##### Values in between Upp-Lower Threshold : considered only if the connected pixel is from upper thresold values

In [52]:
import numpy as np
import cv2 as cv
def something(x):
    pass
# Create a black image, a window
img = cv.imread('book.jpg',0)
img=cv.resize(img,(600,400),cv.INTER_AREA)
cv.namedWindow('image')
# create trackbars for color change
cv.createTrackbar('min','image',0,1000,something)
cv.createTrackbar('max','image',0,1000,something)
# create switch for ON/OFF functionality
switch = "0 : OFF \n 1 : ON"
cv.createTrackbar(switch, 'image',0,1,something)
while(1):
    # get current positions of four trackbars
    g = cv.getTrackbarPos ('min', 'image')
    b = cv.getTrackbarPos ('max', 'image')
    s = cv.getTrackbarPos (switch, 'image')
    if s == 0:
        img=img
        edges=img
    if s==1:
        edges = cv.Canny(img,g,b)
    cv.imshow ('image', edges)
    k = cv.waitKey (1) & 0xFF
    if k == 27:
        break
cv.destroyAllWindows()

In [90]:
pin=[1,2,3,4,5]
for i in range(len(pin)-1):
    for j in range(len(pin)-i-1):
        print(pin[i],pin[j+1+i])

1 2
1 3
1 4
1 5
2 3
2 4
2 5
3 4
3 5
4 5


# Part 2
### Homography and stitching an image

##### Visualising SIFT features

In [145]:
import cv2

# Load an image
image = cv2.imread('PA120274.JPG')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Create a SIFT object
sift = cv2.SIFT_create()

# Detect keypoints and compute descriptors
keypoints, descriptors = sift.detectAndCompute(gray, None)

# Draw keypoints on the image
image_with_keypoints = cv2.drawKeypoints(image, keypoints, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# Display the result
cv2.imshow('SIFT Keypoints', image_with_keypoints)
cv2.waitKey(0)
cv2.destroyAllWindows()


##### Matching SIFT features between 2 consecutive images

In [186]:
import cv2
import numpy as np

# Load two images
image1 = cv2.imread('PA120275.JPG')
image2 = cv2.imread('PA120274.JPG')

# Convert images to grayscale
gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

# Create SIFT object
sift = cv2.SIFT_create()

# Detect keypoints and compute descriptors for both images
keypoints1, descriptors1 = sift.detectAndCompute(gray1, None)
keypoints2, descriptors2 = sift.detectAndCompute(gray2, None)

# Create a BFMatcher object
bf = cv2.BFMatcher()

# Match descriptors
matches = bf.knnMatch(descriptors1, descriptors2, k=2)

# Apply ratio test
good_matches = []
for m, n in matches:
    if m.distance < 0.75 * n.distance:
        good_matches.append(m)

# Draw matches
matched_image = cv2.drawMatches(image1, keypoints1, image2, keypoints2, good_matches, None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

# Display the result
cv2.imshow('Matched Features', matched_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


##### Computing Homography between the pair of images

In [4]:
#defining Resize of image
def resizeImage(image, percentage):
  """Function to resize an image by given percentage
  """
  original_height, original_width = image.shape[:2]

  new_height = int(original_height * (percentage / 100))
  new_width = int(original_width * (percentage / 100))

  resized_img = cv2.resize(image, (new_width, new_height))

  return resized_img

##### Joining 273 and 272
##### where 272 is source image on which homo trnasform wll be applied and 273 will be kept as it is

In [64]:
import cv2
import numpy as np

# Load two images
image_1 = cv2.imread('PA120272.JPG')
image_2 = cv2.imread('PA120273.JPG')

# Resize the image
image1 = resizeImage(image_1, 50)
# Resize the image
image2 = resizeImage(image_2, 50)

# Convert images to grayscale
gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

# Create SIFT object
sift = cv2.SIFT_create()

# Detect keypoints and compute descriptors for both images
keypoints1, descriptors1 = sift.detectAndCompute(gray1, None)
keypoints2, descriptors2 = sift.detectAndCompute(gray2, None)

# Create a BFMatcher object
bf = cv2.BFMatcher()

# Match descriptors
matches = bf.knnMatch(descriptors1, descriptors2, k=2)

# Apply ratio test
good_matches = []
for m, n in matches:
    if m.distance < 0.75 * n.distance:
        good_matches.append(m)

# Extract keypoints for the good matches
src_pts = np.float32([keypoints1[m.queryIdx].pt for m in good_matches]).reshape(-1, 2)
dst_pts = np.float32([keypoints2[m.trainIdx].pt for m in good_matches]).reshape(-1, 2)

# Estimate homography using RANSAC
homography, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)
print(homography)

# Apply homography to image1 to warp it onto image2
height, width, _ = image1.shape
warped_image1 = cv2.warpPerspective(image1, homography, (image2.shape[1] +image1.shape[1], height))
warped_image1[:image2.shape[0],:image2.shape[1]]=image2


def trim(frame):
    if not np.sum(frame[0]):
        return trim(frame[1:])
    if not np.sum(frame[-1]):
        return trim(frame[:-2])
    if not np.sum(frame[:,0]):
        return trim(frame[:,1:])
    if not np.sum(frame[:,-1]):
        return trim(frame[:,:-2])
    return frame


warped_image1__=trim(warped_image1)
# Display the result
cv2.imshow('RANSAC Matches', warped_image1__)
cv2.imwrite('warped_image23.jpg', warped_image1__)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[ 8.41215807e-01  5.59591722e-02  1.64579418e+02]
 [-1.15982217e-01  9.73796679e-01  1.21197103e+01]
 [-5.50690447e-04  6.61437139e-05  1.00000000e+00]]


##### Joining 275 and 274
##### where 275 is source image on which homo trnasform wll be applied and 274 will be kept as it is

In [75]:
# Load two images
image_1 = cv2.imread('PA120275.JPG')#warped_image1__
image_2 = cv2.imread('PA120274.JPG')

# Resize the image
image1 = resizeImage(image_1, 50)
# Resize the image
image2 = resizeImage(image_2, 50)

# Convert images to grayscale
gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

# Create SIFT object
sift = cv2.SIFT_create()

# Detect keypoints and compute descriptors for both images
keypoints1, descriptors1 = sift.detectAndCompute(gray1, None)
keypoints2, descriptors2 = sift.detectAndCompute(gray2, None)

# Create a BFMatcher object
bf = cv2.BFMatcher()

# Match descriptors
matches = bf.knnMatch(descriptors1, descriptors2, k=2)

# Apply ratio test
good_matches = []
for m, n in matches:
    if m.distance < 0.75 * n.distance:
        good_matches.append(m)

# Extract keypoints for the good matches
src_pts = np.float32([keypoints1[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
dst_pts = np.float32([keypoints2[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)

# Estimate homography using RANSAC
homography, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)
print(homography)
homo=homography
#need to trnaslate the transformed image to mix with destination image
homo[0,2]=180
print(homo)

# Apply homography to image1 to warp it onto image2
height, width, _ = image1.shape
warped_image2 = cv2.warpPerspective(image1, homo, (image2.shape[1] +image1.shape[1], height))

#here we are adding image from half way through hence mentioned:
#if image is 640x240
# image[0:240, 320:640 ]= image_other
warped_image2[0:image2.shape[0],image2.shape[1]+0:image2.shape[1]+image2.shape[1]]=image2



def trim(frame):
    if not np.sum(frame[0]):
        return trim(frame[1:])
    if not np.sum(frame[-1]):
        return trim(frame[:-2])
    if not np.sum(frame[:,0]):
        return trim(frame[:,1:])
    if not np.sum(frame[:,-1]):
        return trim(frame[:,:-2])
    return frame

warped_image2__=trim(warped_image2)
# Display the result
cv2.imshow('RANSAC Matches', warped_image2__)
# cv2.imwrite('wraped_image34.jpg',warped_image2__)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[ 1.10766554e+00 -6.81310226e-02 -1.57422329e+02]
 [ 1.05351620e-01  1.06748416e+00 -2.58863170e+01]
 [ 4.27960510e-04 -8.94591929e-05  1.00000000e+00]]
[[ 1.10766554e+00 -6.81310226e-02  1.80000000e+02]
 [ 1.05351620e-01  1.06748416e+00 -2.58863170e+01]
 [ 4.27960510e-04 -8.94591929e-05  1.00000000e+00]]


##### wrapping the above two images into one image

In [63]:
# Load two images
image_1 = warped_image1__ # cv2.imread('PA120274.JPG')
image_2 = warped_image2__

# Resize the image
image1 = resizeImage(image_1, 100)
# Resize the image
image2 = resizeImage(image_2, 100)

# Convert images to grayscale
gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

# Create SIFT object
sift = cv2.SIFT_create()

# Detect keypoints and compute descriptors for both images
keypoints1, descriptors1 = sift.detectAndCompute(gray1, None)
keypoints2, descriptors2 = sift.detectAndCompute(gray2, None)

# Create a BFMatcher object
bf = cv2.BFMatcher()

# Match descriptors
matches = bf.knnMatch(descriptors1, descriptors2, k=2)

# Apply ratio test
good_matches = []
for m, n in matches:
    if m.distance < 0.75 * n.distance:
        good_matches.append(m)

# Extract keypoints for the good matches
src_pts = np.float32([keypoints1[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
dst_pts = np.float32([keypoints2[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)

# Estimate homography using RANSAC
homography, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)
print(homography)
# homo=homography
# homo[0,2]=200

# Apply homography to image1 to warp it onto image2
height, width, _ = image1.shape
warped_image3 = cv2.warpPerspective(image1, homography, (image2.shape[1] +image1.shape[1], height))
warped_image3[0:image2.shape[0],0:image2.shape[1]]=image2
# warped_image3[0:image2.shape[0],image1.shape[1]+0:image2.shape[1]+image1.shape[1]]=image2

def trim(frame):
    if not np.sum(frame[0]):
        return trim(frame[1:])
    if not np.sum(frame[-1]):
        return trim(frame[:-2])
    if not np.sum(frame[:,0]):
        return trim(frame[:,1:])
    if not np.sum(frame[:,-1]):
        return trim(frame[:,:-2])
    return frame

warped_image3__=trim(warped_image3)
# Display the result
cv2.imshow('RANSAC Matches', warped_image3__)
cv2.imwrite('wraped_full.jpg',warped_image3__)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[ 8.03222859e-01  7.55191131e-03  2.88727329e+02]
 [-1.11867591e-01  9.19336610e-01  1.78586813e+01]
 [-3.83902182e-04 -1.66034364e-04  1.00000000e+00]]
